// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type CoreCustomer struct {
	ID           int32
	CustomerCode string
	Name         string
	Email        sql.NullString
	Phone        sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type CoreProduct struct {
	ID          int32
	ProductCode string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CoreQuote struct {
	ID          int32
	QuoteCode   sql.NullString
	CustomerID  int32
	Status      string
	TotalAmount float64
	Currency    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CoreQuoteProduct struct {
	ID           int32
	QuoteID      int32
	ProductID    int32
	Quantity     int32
	PricePerUnit float64
	TaxRate      float64
	TotalPrice   float64
	CreatedAt    sql.NullTime
}
